In [26]:
import matplotlib.pyplot as plt
import numpy as np
from MySequencial import MySequencial
from DenseLayer import DenseLayer
import pandas as pd
from ActivationFunctions import sigmoid, relu, linear, softmax, relu_deriv, softmax_deriv, sigmoid_deriv
from LossFunctions import binaryCrossentropyLoss


In [34]:
layers = [1, 2, 3, 4]
for i in reversed(range(1, len(layers)-1)):
    print(i)

2
1


In [2]:
X_tstn = np.array([[-0.47,  0.42],
       [-0.47,  3.16],
        [-0.5,  3.0]])

W1_tmp = np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
b1_tmp = np.array( [-9.82, -9.28,  0.96] )
W2_tmp = np.array( [[-31.18, 0.2], [-27.59, -0.2], [-32.56, 0.2]] )
b2_tmp = np.array( [15.41] )
y_tstn = np.array([1,0,0])


In [3]:
X_tstn.shape[0]

3

In [4]:
modeltest = MySequencial([
    DenseLayer(2, activation="linear"), 
    DenseLayer(3, activation='sigmoid'),
    DenseLayer(2, activation='softmax')
])


In [5]:
modeltest.summary()

----------- Layer 1 -----------
Layer Name: Dense 1 (input)
Input Layer : True
Shape W: (2, 2)
Shape b: (1, 2)
activation: linear
weights_initializer: heUniformWI 

----------- Layer 2 -----------
Layer Name: Dense 2
Input Layer : False
Shape W: (2, 3)
Shape b: (1, 3)
activation: sigmoid
weights_initializer: heUniformWI 

----------- Layer 3 -----------
Layer Name: Dense 3
Input Layer : False
Shape W: (3, 2)
Shape b: (1, 2)
activation: softmax
weights_initializer: heUniformWI 



In [6]:
modeltest.predict(X_tstn)

[array([0.2496739, 0.7503261]),
 array([0.20114685, 0.79885315]),
 array([0.20075651, 0.79924349])]

In [7]:
modeltest.layers[2].setErrorLastLayer(y_tstn)


Dense 3
error [[ 0.2496739  -0.2496739 ]
 [-0.79885315  0.79885315]
 [-0.79924349  0.79924349]]
delta [array([ 0.05866492, -0.05866492]), array([-0.18288695,  0.18288695]), array([-0.18293483,  0.18293483])]


In [8]:
delta_lastLayer = [np.array([ 0.17797117, -0.17797117]),
                np.array([-0.10354539,  0.10354539]),
                np.array([-0.10120978,  0.10120978])]

In [9]:
W_hiden = modeltest.layers[1].W
W_hiden

array([[ 1.45991311, -0.95834371, -0.48713683],
       [ 0.06551946,  0.13654058,  1.57681532]])

In [10]:
input = modeltest.layers[1].input
input

[array([-0.47,  0.42]), array([-0.47,  3.16]), array([-0.5,  3. ])]

In [11]:
input @ W_hiden

array([[-0.65864099,  0.50776859,  0.89121674],
       [-0.47911767,  0.88188979,  5.21169073],
       [-0.53339817,  0.88879361,  4.97401438]])

In [12]:
-0.47 * -0.50005774 + 0.42 *  1.10681191

0.69988814

In [13]:
delta_lastLayer @ W_hiden

array([[ 0.24816187, -0.19485784, -0.36732398],
       [-0.14438303,  0.11337022,  0.21371273],
       [-0.14112627,  0.110813  ,  0.20889214]])

In [14]:
W_hiden

array([[ 1.45991311, -0.95834371, -0.48713683],
       [ 0.06551946,  0.13654058,  1.57681532]])

In [15]:
Delta_out = modeltest.layers[2].delta
Delta_out

[array([ 0.05866492, -0.05866492]),
 array([-0.18288695,  0.18288695]),
 array([-0.18293483,  0.18293483])]

In [16]:
Err = Delta_out @ W_hiden
Err

array([[ 0.08180199, -0.06423129, -0.12108158],
       [-0.2550164 ,  0.20024005,  0.37746992],
       [-0.25508317,  0.20029247,  0.37756874]])

In [17]:
hidden_out = modeltest.layers[1].output
hidden_out

[array([0.34104496, 0.62428323, 0.7091412 ]),
 array([0.3824605 , 0.70721368, 0.99457712]),
 array([0.36972467, 0.70864115, 0.99313216])]

In [21]:
deriv = [relu_deriv(out) for out in hidden_out]
deriv

[array([1, 1, 1]), array([1, 1, 1]), array([1, 1, 1])]

In [24]:
deriv[1][2] = 0
Err * deriv

array([[ 0.08180199, -0.06423129, -0.12108158],
       [-0.2550164 ,  0.20024005,  0.        ],
       [-0.25508317,  0.20029247,  0.37756874]])

In [19]:
modeltest.layers[1].setError(modeltest.layers[2])


Dense 2
error [[ 0.09665574  0.01851708  0.30093466]
 [-0.11391839 -0.02182422 -0.35468139]
 [-0.11457789 -0.02195056 -0.35673474]]


In [23]:
F_wb = modeltest.predict(X_tstn)
print(np.log(F_wb))
Y_bis = Y.reshape(F_wb.shape)
print(Y_bis)
print()
print(-(Y_bis * np.log(F_wb) + (1 - Y_bis) * np.log(1 - F_wb)))

sum(-(Y_bis * np.log(F_wb) + (1 - Y_bis) * np.log(1 - F_wb)))
# cost = -(Y * np.log(F_wb) + (1 - Y) * np.log(1 - F_wb))
#     cost = cost / m + (lambda_ / (2*m)) * np.sum(w**2)
#     return (cost)


[[-1.98369577e-09]
 [-2.07181375e+01]
 [-2.07449450e+01]]
[[1]
 [0]
 [0]]

[[1.98369577e-09]
 [1.00514153e-09]
 [9.78554127e-10]]


array([3.96739142e-09])

In [24]:
cost = modeltest.cost(X_tstn, Y)

In [25]:
cost

1.3224638061150563e-09

In [26]:
binaryCrossentropyLoss(modeltest, X_tstn, Y)

array([[1.98369577e-09],
       [1.00514153e-09],
       [9.78554127e-10]])

In [27]:
f = np.array([[9.70292454e-01],
 [3.28294082e-08],
 [3.19610272e-08]])


In [28]:
result = []
for i in range(len(Y)):
    result.append(-Y[i] * np.log(f[i]) - (1 - Y[i]) * np.log(1 - f[i]))

In [31]:
my_predictions = modeltest.predict(X_tstn)

In [32]:
yhat = (my_predictions >= 0.5).astype(int)
print(f"decisions = \n{yhat}")

decisions = 
[[1]
 [0]
 [0]]


In [33]:
df = pd.read_csv("data.csv",header=None)

In [44]:
dfnp = df.to_numpy()

In [68]:
dfnp[0:16]

array([[842302, 'M', 17.99, 10.38, 122.8, 1001.0, 0.1184, 0.2776, 0.3001,
        0.1471, 0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399,
        0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33,
        184.6, 2019.0, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189],
       [842517, 'M', 20.57, 17.77, 132.9, 1326.0, 0.08474, 0.07864,
        0.0869, 0.07017, 0.1812, 0.05667, 0.5435, 0.7339, 3.398, 74.08,
        0.005225, 0.01308, 0.0186, 0.0134, 0.01389, 0.003532, 24.99,
        23.41, 158.8, 1956.0, 0.1238, 0.1866, 0.2416, 0.186, 0.275,
        0.08902],
       [84300903, 'M', 19.69, 21.25, 130.0, 1203.0, 0.1096, 0.1599,
        0.1974, 0.1279, 0.2069, 0.05999, 0.7456, 0.7869, 4.585, 94.03,
        0.00615, 0.04006, 0.03832, 0.02058, 0.0225, 0.004571, 23.57,
        25.53, 152.5, 1709.0, 0.1444, 0.4245, 0.4504, 0.243, 0.3613,
        0.08758],
       [84348301, 'M', 11.42, 20.38, 77.58, 386.1, 0.1425, 0.2839,
        0.2414, 0.1052, 0.2597, 0.09744, 0.4956, 1.156, 3

In [73]:
batch_size = 3
mini_batchs = [dfnp[i:i+batch_size,0] for i in range(0, len(dfnp), batch_size)]
mini_batchs


[array([842302, 842517, 84300903], dtype=object),
 array([84348301, 84358402, 843786], dtype=object),
 array([844359, 84458202, 844981], dtype=object),
 array([84501001, 845636, 84610002], dtype=object),
 array([846226, 846381, 84667401], dtype=object),
 array([84799002, 848406, 84862001], dtype=object),
 array([849014, 8510426, 8510653], dtype=object),
 array([8510824, 8511133, 851509], dtype=object),
 array([852552, 852631, 852763], dtype=object),
 array([852781, 852973, 853201], dtype=object),
 array([853401, 853612, 85382601], dtype=object),
 array([854002, 854039, 854253], dtype=object),
 array([854268, 854941, 855133], dtype=object),
 array([855138, 855167, 855563], dtype=object),
 array([855625, 856106, 85638502], dtype=object),
 array([857010, 85713702, 85715], dtype=object),
 array([857155, 857156, 857343], dtype=object),
 array([857373, 857374, 857392], dtype=object),
 array([857438, 85759902, 857637], dtype=object),
 array([857793, 857810, 858477], dtype=object),
 array([858

In [75]:
np.random.shuffle(mini_batchs)
mini_batchs

[array([89511501, 89511502, 89524], dtype=object),
 array([91504, 91505, 915143], dtype=object),
 array([899667, 899987, 9010018], dtype=object),
 array([908489, 908916, 909220], dtype=object),
 array([86408, 86409, 864292], dtype=object),
 array([914769, 91485, 914862], dtype=object),
 array([904971, 905189, 905190], dtype=object),
 array([863030, 863031, 863270], dtype=object),
 array([91544002, 915452, 915460], dtype=object),
 array([897137, 897374, 89742801], dtype=object),
 array([874839, 874858, 875093], dtype=object),
 array([881046502, 8810528, 8810703], dtype=object),
 array([89812, 89813, 898143], dtype=object),
 array([895299, 8953902, 895633], dtype=object),
 array([865137, 86517, 865423], dtype=object),
 array([8712766, 8712853, 87139402], dtype=object),
 array([8912521, 8912909, 8913], dtype=object),
 array([88350402, 883539, 883852], dtype=object),
 array([875878, 875938, 877159], dtype=object),
 array([87930, 879523, 879804], dtype=object),
 array([898690, 899147, 89918

In [70]:
epochs =  15
nb_batch = 100

for epoch in range(epochs):
    for num_batch in range(nb_batch):
        print(f"epoch {epoch} : {num_batch + 1}/{nb_batch}\r" , end='', flush=True)
        
    print()

epoch 0 : 100/100
epoch 1 : 100/100
epoch 2 : 100/100
epoch 3 : 100/100
epoch 4 : 100/100
epoch 5 : 100/100
epoch 6 : 100/100
epoch 7 : 100/100
epoch 8 : 100/100
epoch 9 : 100/100
epoch 10 : 100/100
epoch 11 : 100/100
epoch 12 : 100/100
epoch 13 : 100/100
epoch 14 : 100/100


In [ ]:
np.diag(np.ones(10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# network = model.createNetwork([
# layers.DenseLayer(input_shape, activation='sigmoid'),
# layers.DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
# layers.DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
# layers.DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
# layers.DenseLayer(output_shape, activation='softmax', weights_initializer='heUniform')
# ])

In [3]:
dense1 = DenseLayer(30, activation="relu", layerName="dense1")
dense1.input_shape

30

In [2]:
model = MySequencial([
    DenseLayer(30, activation="relu", layerName="dense1"), 
    DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
    DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
    DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
    DenseLayer(2, activation='softmax', weights_initializer='heUniform')
])


In [54]:
b = np.array([0.1, 0.2, 0.3])

In [55]:
b

array([0.1, 0.2, 0.3])

In [73]:
a = np.array([0.5, 1])

In [67]:
a.transpose()

array([ 0.5, -0.5])

In [79]:
z = W.transpose() @ a + b

In [81]:
def test(z):
    return z + 1
print(z)
test(z)

[4.6 6.2 7.8]


array([5.6, 7.2, 8.8])

In [7]:
X = np.array([[185.32,  12.69],
       [259.92,  11.87],
       [231.01,  14.41],
       [175.37,  11.72],
       [187.12,  14.13],
       [225.91,  12.1 ],
       [208.41,  14.18],
       [207.08,  14.03],
       [280.6 ,  14.23],
       [202.87,  12.25],
       [196.7 ,  13.54],
       [270.31,  14.6 ],
       [192.95,  15.2 ],
       [213.57,  14.28],
       [164.47,  11.92],
       [177.26,  15.04],
       [241.77,  14.9 ],
       [237.  ,  13.13],
       [219.74,  13.87],
       [266.39,  13.25],
       [270.45,  13.95],
       [261.96,  13.49],
       [243.49,  12.86],
       [220.58,  12.36],
       [163.59,  11.65],
       [244.76,  13.33],
       [271.19,  14.84],
       [201.99,  15.39],
       [229.93,  14.56],
       [204.97,  12.28],
       [173.19,  12.22],
       [231.51,  11.95],
       [152.69,  14.83],
       [163.42,  13.3 ],
       [215.95,  13.98],
       [218.04,  15.25],
       [251.3 ,  13.8 ],
       [233.33,  13.53],
       [280.24,  12.41],
       [243.02,  13.72],
       [155.67,  12.68],
       [275.17,  14.64],
       [151.73,  12.69],
       [151.32,  14.81],
       [164.9 ,  11.73],
       [282.55,  13.28],
       [192.98,  11.7 ],
       [202.6 ,  12.96],
       [220.67,  11.53],
       [169.97,  12.34],
       [209.47,  12.71],
       [232.8 ,  12.64],
       [272.8 ,  15.35],
       [158.02,  12.34],
       [226.01,  14.58],
       [158.64,  12.24],
       [211.66,  14.17],
       [271.95,  14.97],
       [257.16,  11.71],
       [281.85,  13.96],
       [161.63,  12.52],
       [233.8 ,  13.04],
       [210.29,  14.72],
       [261.24,  13.69],
       [256.98,  13.12],
       [281.56,  13.92],
       [280.64,  11.68],
       [269.16,  13.74],
       [246.34,  12.27],
       [224.07,  12.66],
       [164.24,  11.51],
       [272.42,  14.18],
       [177.68,  12.53],
       [212.86,  14.77],
       [165.88,  15.37],
       [277.43,  12.48],
       [236.51,  12.94],
       [244.14,  11.85],
       [213.45,  13.85],
       [234.57,  14.27],
       [270.34,  12.47],
       [170.68,  13.06],
       [226.79,  15.34],
       [245.92,  14.45],
       [281.32,  12.57],
       [185.03,  13.19],
       [189.88,  14.1 ],
       [278.48,  12.11],
       [219.92,  14.21],
       [216.58,  15.15],
       [249.48,  15.03],
       [165.09,  12.28],
       [158.87,  14.82],
       [279.98,  11.56],
       [256.55,  14.41],
       [272.61,  12.58],
       [246.49,  12.45],
       [160.26,  14.48],
       [155.7 ,  14.3 ],
       [188.27,  13.45],
       [270.36,  12.47],
       [213.22,  12.92],
       [175.7 ,  13.39],
       [174.52,  14.7 ],
       [233.  ,  12.63],
       [281.37,  12.88],
       [240.62,  14.43],
       [185.81,  11.55],
       [270.5 ,  15.33],
       [172.98,  12.11],
       [208.41,  13.89],
       [283.51,  15.35],
       [283.36,  12.48],
       [230.85,  13.24],
       [181.24,  11.76],
       [172.78,  12.93],
       [161.88,  12.1 ],
       [156.03,  13.99],
       [216.52,  12.47],
       [221.06,  13.2 ],
       [238.99,  15.23],
       [197.69,  14.08],
       [179.55,  15.26],
       [233.39,  12.13],
       [184.7 ,  12.14],
       [174.18,  12.73],
       [261.11,  13.33],
       [187.42,  13.18],
       [186.1 ,  14.43],
       [157.94,  12.66],
       [193.64,  12.23],
       [249.65,  12.22],
       [190.56,  11.73],
       [252.  ,  12.96],
       [238.55,  12.37],
       [152.94,  12.79],
       [255.17,  14.85],
       [197.09,  14.89],
       [156.8 ,  13.59],
       [184.75,  13.26],
       [179.92,  15.07],
       [190.79,  15.28],
       [164.73,  13.22],
       [209.87,  14.34],
       [196.58,  13.47],
       [159.51,  12.74],
       [247.87,  11.92],
       [212.44,  12.45],
       [172.34,  11.99],
       [259.87,  14.25],
       [201.23,  13.07],
       [248.34,  13.92],
       [273.66,  15.18],
       [215.09,  14.14],
       [223.53,  12.74],
       [211.22,  14.38],
       [224.61,  14.03],
       [215.75,  15.31],
       [254.82,  12.02],
       [259.9 ,  15.17],
       [260.25,  12.87],
       [199.67,  12.47],
       [157.52,  13.39],
       [264.81,  14.58],
       [239.4 ,  14.89],
       [238.98,  12.39],
       [258.43,  12.97],
       [270.16,  12.81],
       [162.41,  14.42],
       [164.53,  14.98],
       [205.61,  14.62],
       [157.1 ,  13.68],
       [241.38,  12.02],
       [232.13,  12.07],
       [191.04,  12.96],
       [233.64,  12.02],
       [174.95,  14.63],
       [246.64,  13.32],
       [188.07,  14.27],
       [213.16,  12.75],
       [268.08,  12.31],
       [258.58,  13.97],
       [237.21,  14.23],
       [251.02,  15.02],
       [274.28,  12.52],
       [172.12,  15.09],
       [177.52,  12.39],
       [258.71,  15.36],
       [264.01,  13.57],
       [200.71,  15.45],
       [249.37,  14.02],
       [151.5 ,  12.28],
       [151.82,  15.13],
       [181.92,  12.18],
       [228.65,  12.31],
       [223.78,  15.3 ],
       [266.63,  12.48],
       [273.68,  13.1 ],
       [220.61,  12.8 ],
       [284.99,  12.73]])

In [2]:
Y = np.array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [2]:
# print(f"Temperature Max, Min pre normalization: {np.max(X[:,0]):0.2f}, {np.min(X[:,0]):0.2f}")
# print(f"Duration    Max, Min pre normalization: {np.max(X[:,1]):0.2f}, {np.min(X[:,1]):0.2f}")
# norm_l = tf.keras.layers.Normalization(axis=-1)
# norm_l.adapt(X)  # learns mean, variance
# Xn = norm_l(X)
# print(f"Temperature Max, Min post normalization: {np.max(Xn[:,0]):0.2f}, {np.min(Xn[:,0]):0.2f}")
# print(f"Duration    Max, Min post normalization: {np.max(Xn[:,1]):0.2f}, {np.min(Xn[:,1]):0.2f}")
Xn = np.array([[-0.83, -0.65],
       [ 1.03, -1.39],
       [ 0.31,  0.87],
       [-1.08, -1.52],
       [-0.79,  0.62],
       [ 0.18, -1.18],
       [-0.26,  0.66],
       [-0.29,  0.53],
       [ 1.55,  0.71],
       [-0.4 , -1.05],
       [-0.55,  0.1 ],
       [ 1.29,  1.04],
       [-0.64,  1.57],
       [-0.13,  0.75],
       [-1.36, -1.34],
       [-1.04,  1.42],
       [ 0.58,  1.3 ],
       [ 0.46, -0.27],
       [ 0.03,  0.39],
       [ 1.19, -0.16],
       [ 1.3 ,  0.46],
       [ 1.08,  0.05],
       [ 0.62, -0.51],
       [ 0.05, -0.94],
       [-1.38, -1.57],
       [ 0.65, -0.09],
       [ 1.31,  1.25],
       [-0.42,  1.74],
       [ 0.28,  1.  ],
       [-0.34, -1.02],
       [-1.14, -1.07],
       [ 0.32, -1.31],
       [-1.65,  1.24],
       [-1.38, -0.11],
       [-0.07,  0.49],
       [-0.02,  1.61],
       [ 0.82,  0.33],
       [ 0.37,  0.08],
       [ 1.54, -0.91],
       [ 0.61,  0.26],
       [-1.58, -0.66],
       [ 1.41,  1.07],
       [-1.67, -0.66],
       [-1.69,  1.22],
       [-1.35, -1.51],
       [ 1.6 , -0.13],
       [-0.64, -1.54],
       [-0.4 , -0.41],
       [ 0.05, -1.69],
       [-1.22, -0.97],
       [-0.23, -0.64],
       [ 0.35, -0.7 ],
       [ 1.35,  1.7 ],
       [-1.52, -0.97],
       [ 0.18,  1.02],
       [-1.5 , -1.06],
       [-0.18,  0.66],
       [ 1.33,  1.36],
       [ 0.96, -1.52],
       [ 1.58,  0.47],
       [-1.43, -0.81],
       [ 0.38, -0.34],
       [-0.21,  1.14],
       [ 1.07,  0.23],
       [ 0.96, -0.27],
       [ 1.57,  0.43],
       [ 1.55, -1.56],
       [ 1.26,  0.27],
       [ 0.69, -1.03],
       [ 0.14, -0.69],
       [-1.36, -1.7 ],
       [ 1.35,  0.67],
       [-1.03, -0.8 ],
       [-0.15,  1.19],
       [-1.32,  1.72],
       [ 1.47, -0.84],
       [ 0.45, -0.43],
       [ 0.64, -1.4 ],
       [-0.13,  0.38],
       [ 0.4 ,  0.74],
       [ 1.29, -0.86],
       [-1.2 , -0.33],
       [ 0.2 ,  1.69],
       [ 0.68,  0.91],
       [ 1.57, -0.76],
       [-0.84, -0.21],
       [-0.72,  0.6 ],
       [ 1.5 , -1.17],
       [ 0.03,  0.69],
       [-0.05,  1.53],
       [ 0.77,  1.42],
       [-1.34, -1.02],
       [-1.5 ,  1.23],
       [ 1.53, -1.66],
       [ 0.95,  0.87],
       [ 1.35, -0.75],
       [ 0.7 , -0.87],
       [-1.46,  0.93],
       [-1.58,  0.77],
       [-0.76,  0.02],
       [ 1.29, -0.85],
       [-0.14, -0.45],
       [-1.08, -0.03],
       [-1.1 ,  1.12],
       [ 0.36, -0.71],
       [ 1.57, -0.49],
       [ 0.55,  0.89],
       [-0.82, -1.67],
       [ 1.3 ,  1.68],
       [-1.14, -1.17],
       [-0.26,  0.41],
       [ 1.62,  1.7 ],
       [ 1.62, -0.84],
       [ 0.3 , -0.17],
       [-0.94, -1.48],
       [-1.15, -0.44],
       [-1.42, -1.18],
       [-1.57,  0.5 ],
       [-0.05, -0.85],
       [ 0.06, -0.21],
       [ 0.51,  1.6 ],
       [-0.52,  0.58],
       [-0.98,  1.62],
       [ 0.37, -1.15],
       [-0.85, -1.15],
       [-1.11, -0.62],
       [ 1.06, -0.09],
       [-0.78, -0.23],
       [-0.82,  0.89],
       [-1.52, -0.69],
       [-0.63, -1.07],
       [ 0.78, -1.07],
       [-0.7 , -1.51],
       [ 0.83, -0.42],
       [ 0.5 , -0.94],
       [-1.64, -0.57],
       [ 0.91,  1.26],
       [-0.54,  1.29],
       [-1.55,  0.14],
       [-0.85, -0.15],
       [-0.97,  1.46],
       [-0.7 ,  1.64],
       [-1.35, -0.19],
       [-0.22,  0.8 ],
       [-0.55,  0.03],
       [-1.48, -0.61],
       [ 0.73, -1.34],
       [-0.16, -0.87],
       [-1.16, -1.28],
       [ 1.03,  0.72],
       [-0.44, -0.32],
       [ 0.74,  0.43],
       [ 1.38,  1.55],
       [-0.09,  0.63],
       [ 0.12, -0.61],
       [-0.19,  0.85],
       [ 0.15,  0.53],
       [-0.07,  1.67],
       [ 0.9 , -1.25],
       [ 1.03,  1.54],
       [ 1.04, -0.49],
       [-0.48, -0.85],
       [-1.53, -0.04],
       [ 1.15,  1.01],
       [ 0.52,  1.29],
       [ 0.51, -0.92],
       [ 0.99, -0.41],
       [ 1.29, -0.55],
       [-1.41,  0.88],
       [-1.35,  1.37],
       [-0.33,  1.05],
       [-1.54,  0.22],
       [ 0.57, -1.25],
       [ 0.34, -1.2 ],
       [-0.69, -0.42],
       [ 0.37, -1.25],
       [-1.09,  1.06],
       [ 0.7 , -0.1 ],
       [-0.77,  0.74],
       [-0.14, -0.61],
       [ 1.24, -1.  ],
       [ 1.  ,  0.48],
       [ 0.46,  0.71],
       [ 0.81,  1.41],
       [ 1.39, -0.81],
       [-1.16,  1.47],
       [-1.03, -0.92],
       [ 1.  ,  1.71],
       [ 1.13,  0.12],
       [-0.45,  1.79],
       [ 0.77,  0.52],
       [-1.68, -1.02],
       [-1.67,  1.5 ],
       [-0.92, -1.1 ],
       [ 0.25, -0.99],
       [ 0.13,  1.66],
       [ 1.2 , -0.84],
       [ 1.38, -0.3 ],
       [ 0.05, -0.56],
       [ 1.66, -0.62]])

In [4]:
def my_dense(a_in, W, b):
    """
    Computes dense layer
    Args:
      a_in (ndarray (n, )) : Data, 1 example 
      W    (ndarray (n,j)) : Weight matrix, n features per unit, j units
      b    (ndarray (j, )) : bias vector, j units  
    Returns
      a_out (ndarray (j,))  : j units|
    """
    units = W.shape[1]
    a_out = np.zeros(units)
    for j in range(units):               
        w = W[:,j]                                    
        z = np.dot(w, a_in) + b[j]         
        a_out[j] = g(z)               
    return(a_out)

In [5]:
def my_sequential(x, W1, b1, W2, b2):
    a1 = my_dense(x,  W1, b1)
    a2 = my_dense(a1, W2, b2)
    return(a2)

In [6]:
g = sigmoid

In [2]:
W1_tmp = np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
b1_tmp = np.array( [-9.82, -9.28,  0.96] )
W2_tmp = np.array( [[-31.18], [-27.59], [-32.56]] )
b2_tmp = np.array( [15.41] )

In [8]:
def my_predict(X, W1, b1, W2, b2):
    m = X.shape[0]
    p = np.zeros((m,1))
    for i in range(m):
        p[i,0] = my_sequential(X[i], W1, b1, W2, b2)
    return(p)

In [5]:
X_tst = np.array([
    [200,13.9],  # postive example
    [200,17]])   # negative example





In [ ]:
predictions = my_predict(X_tstn, W1_tmp, b1_tmp, W2_tmp, b2_tmp)

In [10]:
predictions
array([[9.70292454e-01],
       [3.28294082e-08]])

array([[9.70292454e-01],
       [3.28294082e-08]])

In [11]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0
print(f"decisions = \n{yhat}")

decisions = 
[[1.]
 [0.]]


In [12]:
yhat = (predictions >= 0.5).astype(int)
print(f"decisions = \n{yhat}")

decisions = 
[[1]
 [0]]


In [3]:
modeltest = MySequencial([
    DenseLayer(2, activation="linear", layerName="input"), 
    DenseLayer(3, activation='sigmoid', W=W1_tmp, b=b1_tmp, layerName="layer 1"),
    DenseLayer(1, activation='sigmoid', W=W2_tmp, b=b2_tmp, layerName="layer 2")
])


In [15]:
modeltest.summary()

----------- Layer 1 -----------
Layer Name: input
Shape W: (2, 2)
W: [[1. 0.]
 [0. 1.]]
Shape b: (2,)
b: [0. 0.]
activation: <function linear at 0x7fbac2267400>
weights_initializer: <function heUniformWI at 0x7fbac2267b50> 

----------- Layer 2 -----------
Layer Name: Dense
Shape W: (2, 3)
W: [[-8.93  0.29 12.9 ]
 [-0.1  -7.32 10.81]]
Shape b: (3,)
b: [-9.82 -9.28  0.96]
activation: <function sigmoid at 0x7fbac22672e0>
weights_initializer: <function heUniformWI at 0x7fbac2267b50> 

----------- Layer 3 -----------
Layer Name: Dense
Shape W: (3, 1)
W: [[-31.18]
 [-27.59]
 [-32.56]]
Shape b: (1,)
b: [15.41]
activation: <function sigmoid at 0x7fbac22672e0>
weights_initializer: <function heUniformWI at 0x7fbac2267b50> 



In [76]:
z = [0.3, 0.6, 0.7]

In [77]:
softmax(z)

array([0.26030255, 0.35137169, 0.38832577])

In [78]:
def softmax_derivative(z):
    s = softmax(z)
    return s * (1 - s)

In [79]:
softmax_derivative(z)

array([0.19254513, 0.22790962, 0.23752887])

In [84]:
s = softmax(z)
s

array([0.26030255, 0.35137169, 0.38832577])

In [82]:
(1 - s)

array([0.73969745, 0.64862831, 0.61167423])

In [86]:
0.35137169 * 0.64862831

0.2279096254665439

In [9]:
# 7 sur un truc de 10
y = 0
expected = np.zeros(10)
expected[y] = 1
print(expected)

y = 2
np.zeros(10)[y]
expected[y] = 1
print(expected)



[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
y = [1,0,1]

In [21]:
expected = np.zeros((3,2))
for i in range(len(y)):
    expected[i][y[i]] = 1
print("expected", expected)

expected [[0. 1.]
 [1. 0.]
 [0. 1.]]


In [26]:
out = modeltest.predict(X_tstn)

In [24]:
modeltest.predict(X_tstn) - expected

array([[ 0.30809644, -0.30809644],
       [-0.56338921,  0.56338921],
       [ 0.43403628, -0.43403628]])

In [25]:
def softmax_deriv(z):
    s = softmax(z)
    return s * (1 - s)

In [28]:
softmax_deriv(out)

array([[0.21224131, 0.23100526],
       [0.22677572, 0.21705782],
       [0.22650251, 0.21735518]])

In [29]:
[softmax_deriv(x) for x in out]

[array([0.24101467, 0.24101467]),
 array([0.24899814, 0.24899814]),
 array([0.24891534, 0.24891534])]

In [30]:
diffs = out - expected
errors = [diff * softmax_deriv(out_) for diff, out_ in zip(diffs, out)]

In [31]:
errors

[array([ 0.07425576, -0.07425576]),
 array([-0.14028286,  0.14028286]),
 array([ 0.10803829, -0.10803829])]

In [32]:
diffs

array([[ 0.30809644, -0.30809644],
       [-0.56338921,  0.56338921],
       [ 0.43403628, -0.43403628]])

In [33]:
0.30809644 * 0.24101467

0.0742557618147748