In [1]:
import matplotlib.pyplot as plt
import numpy as np
from class_declarations import DenseLayer, MySequencial
import pandas as pd

In [11]:
df = pd.read_csv("data.csv",header=None)

In [12]:
df

0  1      2      3       4       5        6        7        8   \
0      842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
564    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          9   ...      22     23      24      25       26       27      28  \
0    0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         29      30       31  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 32 columns]

In [ ]:
(self, nb_Node:int, input_shape:int, activation:str, W = None, b = None, layerName = "Dense")

In [3]:
dense1 = DenseLayer(30, activation="relu", layerName="dense1")
dense1.input_shape

30

In [6]:
model = MySequencial(dense1, dense2, dense3)


In [7]:
model.summary()

----------- Layer 1 -----------
Layer Name: dense1
Shape W: (2, 3)
W: [[0.73205374 0.71521572 0.90140097]
 [0.42237138 0.04692568 0.78056244]]
Shape b: (3,)
b: [0.8075759  0.11551758 0.36834018]
activation: <function relu at 0x7fa7b4e443a0> 

----------- Layer 2 -----------
Layer Name: dense2
Shape W: (2, 10)
W: [[0.37562633 0.40719525 0.81396449 0.67883717 0.3135492  0.37029954
  0.68354348 0.90881961 0.52742485 0.59464147]
 [0.01223486 0.08531014 0.17152502 0.20966055 0.62142675 0.89993532
  0.11381551 0.4159236  0.31301462 0.53414001]]
Shape b: (10,)
b: [0.54448791 0.69645441 0.3809368  0.56254779 0.59884843 0.34549447
 0.3140322  0.82014449 0.99130535 0.33821021]
activation: <function relu at 0x7fa7b4e443a0> 

----------- Layer 3 -----------
Layer Name: dense3
Shape W: (2, 5)
W: [[0.88629109 0.79995798 0.17412533 0.78846854 0.43965777]
 [0.53844094 0.50247974 0.89453641 0.97471191 0.34992956]]
Shape b: (5,)
b: [0.36389583 0.56410006 0.89750039 0.42338177 0.23516636]
activation: <fu

In [43]:
np.random.rand(nb_Node)

array([0.27381691, 0.8566269 , 0.85390372])

In [72]:
W[0] = np.array([1,2,3])
W[1] = np.array([4,5,6])

In [54]:
b = np.array([0.1, 0.2, 0.3])

In [55]:
b

array([0.1, 0.2, 0.3])

In [73]:
a = np.array([0.5, 1])

In [67]:
a.transpose()

array([ 0.5, -0.5])

In [79]:
z = W.transpose() @ a + b

In [81]:
def test(z):
    return z + 1
print(z)
test(z)

[4.6 6.2 7.8]


array([5.6, 7.2, 8.8])

In [2]:
# X = np.array([[185.32,  12.69],
#        [259.92,  11.87],
#        [231.01,  14.41],
#        [175.37,  11.72],
#        [187.12,  14.13],
#        [225.91,  12.1 ],
#        [208.41,  14.18],
#        [207.08,  14.03],
#        [280.6 ,  14.23],
#        [202.87,  12.25],
#        [196.7 ,  13.54],
#        [270.31,  14.6 ],
#        [192.95,  15.2 ],
#        [213.57,  14.28],
#        [164.47,  11.92],
#        [177.26,  15.04],
#        [241.77,  14.9 ],
#        [237.  ,  13.13],
#        [219.74,  13.87],
#        [266.39,  13.25],
#        [270.45,  13.95],
#        [261.96,  13.49],
#        [243.49,  12.86],
#        [220.58,  12.36],
#        [163.59,  11.65],
#        [244.76,  13.33],
#        [271.19,  14.84],
#        [201.99,  15.39],
#        [229.93,  14.56],
#        [204.97,  12.28],
#        [173.19,  12.22],
#        [231.51,  11.95],
#        [152.69,  14.83],
#        [163.42,  13.3 ],
#        [215.95,  13.98],
#        [218.04,  15.25],
#        [251.3 ,  13.8 ],
#        [233.33,  13.53],
#        [280.24,  12.41],
#        [243.02,  13.72],
#        [155.67,  12.68],
#        [275.17,  14.64],
#        [151.73,  12.69],
#        [151.32,  14.81],
#        [164.9 ,  11.73],
#        [282.55,  13.28],
#        [192.98,  11.7 ],
#        [202.6 ,  12.96],
#        [220.67,  11.53],
#        [169.97,  12.34],
#        [209.47,  12.71],
#        [232.8 ,  12.64],
#        [272.8 ,  15.35],
#        [158.02,  12.34],
#        [226.01,  14.58],
#        [158.64,  12.24],
#        [211.66,  14.17],
#        [271.95,  14.97],
#        [257.16,  11.71],
#        [281.85,  13.96],
#        [161.63,  12.52],
#        [233.8 ,  13.04],
#        [210.29,  14.72],
#        [261.24,  13.69],
#        [256.98,  13.12],
#        [281.56,  13.92],
#        [280.64,  11.68],
#        [269.16,  13.74],
#        [246.34,  12.27],
#        [224.07,  12.66],
#        [164.24,  11.51],
#        [272.42,  14.18],
#        [177.68,  12.53],
#        [212.86,  14.77],
#        [165.88,  15.37],
#        [277.43,  12.48],
#        [236.51,  12.94],
#        [244.14,  11.85],
#        [213.45,  13.85],
#        [234.57,  14.27],
#        [270.34,  12.47],
#        [170.68,  13.06],
#        [226.79,  15.34],
#        [245.92,  14.45],
#        [281.32,  12.57],
#        [185.03,  13.19],
#        [189.88,  14.1 ],
#        [278.48,  12.11],
#        [219.92,  14.21],
#        [216.58,  15.15],
#        [249.48,  15.03],
#        [165.09,  12.28],
#        [158.87,  14.82],
#        [279.98,  11.56],
#        [256.55,  14.41],
#        [272.61,  12.58],
#        [246.49,  12.45],
#        [160.26,  14.48],
#        [155.7 ,  14.3 ],
#        [188.27,  13.45],
#        [270.36,  12.47],
#        [213.22,  12.92],
#        [175.7 ,  13.39],
#        [174.52,  14.7 ],
#        [233.  ,  12.63],
#        [281.37,  12.88],
#        [240.62,  14.43],
#        [185.81,  11.55],
#        [270.5 ,  15.33],
#        [172.98,  12.11],
#        [208.41,  13.89],
#        [283.51,  15.35],
#        [283.36,  12.48],
#        [230.85,  13.24],
#        [181.24,  11.76],
#        [172.78,  12.93],
#        [161.88,  12.1 ],
#        [156.03,  13.99],
#        [216.52,  12.47],
#        [221.06,  13.2 ],
#        [238.99,  15.23],
#        [197.69,  14.08],
#        [179.55,  15.26],
#        [233.39,  12.13],
#        [184.7 ,  12.14],
#        [174.18,  12.73],
#        [261.11,  13.33],
#        [187.42,  13.18],
#        [186.1 ,  14.43],
#        [157.94,  12.66],
#        [193.64,  12.23],
#        [249.65,  12.22],
#        [190.56,  11.73],
#        [252.  ,  12.96],
#        [238.55,  12.37],
#        [152.94,  12.79],
#        [255.17,  14.85],
#        [197.09,  14.89],
#        [156.8 ,  13.59],
#        [184.75,  13.26],
#        [179.92,  15.07],
#        [190.79,  15.28],
#        [164.73,  13.22],
#        [209.87,  14.34],
#        [196.58,  13.47],
#        [159.51,  12.74],
#        [247.87,  11.92],
#        [212.44,  12.45],
#        [172.34,  11.99],
#        [259.87,  14.25],
#        [201.23,  13.07],
#        [248.34,  13.92],
#        [273.66,  15.18],
#        [215.09,  14.14],
#        [223.53,  12.74],
#        [211.22,  14.38],
#        [224.61,  14.03],
#        [215.75,  15.31],
#        [254.82,  12.02],
#        [259.9 ,  15.17],
#        [260.25,  12.87],
#        [199.67,  12.47],
#        [157.52,  13.39],
#        [264.81,  14.58],
#        [239.4 ,  14.89],
#        [238.98,  12.39],
#        [258.43,  12.97],
#        [270.16,  12.81],
#        [162.41,  14.42],
#        [164.53,  14.98],
#        [205.61,  14.62],
#        [157.1 ,  13.68],
#        [241.38,  12.02],
#        [232.13,  12.07],
#        [191.04,  12.96],
#        [233.64,  12.02],
#        [174.95,  14.63],
#        [246.64,  13.32],
#        [188.07,  14.27],
#        [213.16,  12.75],
#        [268.08,  12.31],
#        [258.58,  13.97],
#        [237.21,  14.23],
#        [251.02,  15.02],
#        [274.28,  12.52],
#        [172.12,  15.09],
#        [177.52,  12.39],
#        [258.71,  15.36],
#        [264.01,  13.57],
#        [200.71,  15.45],
#        [249.37,  14.02],
#        [151.5 ,  12.28],
#        [151.82,  15.13],
#        [181.92,  12.18],
#        [228.65,  12.31],
#        [223.78,  15.3 ],
#        [266.63,  12.48],
#        [273.68,  13.1 ],
#        [220.61,  12.8 ],
#        [284.99,  12.73]])

In [3]:
# Y = np.array([[1.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [1.],
#        [0.],
#        [0.],
#        [0.],
#        [1.],
#        [0.]])

In [5]:
# print(f"Temperature Max, Min pre normalization: {np.max(X[:,0]):0.2f}, {np.min(X[:,0]):0.2f}")
# print(f"Duration    Max, Min pre normalization: {np.max(X[:,1]):0.2f}, {np.min(X[:,1]):0.2f}")
# norm_l = tf.keras.layers.Normalization(axis=-1)
# norm_l.adapt(X)  # learns mean, variance
# Xn = norm_l(X)
# print(f"Temperature Max, Min post normalization: {np.max(Xn[:,0]):0.2f}, {np.min(Xn[:,0]):0.2f}")
# print(f"Duration    Max, Min post normalization: {np.max(Xn[:,1]):0.2f}, {np.min(Xn[:,1]):0.2f}")

Temperature Max, Min pre normalization: 284.99, 151.32
Duration    Max, Min pre normalization: 15.45, 11.51
Temperature Max, Min post normalization: 1.66, -1.69
Duration    Max, Min post normalization: 1.79, -1.70
