In [1]:
import matplotlib.pyplot as plt
import numpy as np
from class_declarations import DenseLayer, MySequencial
import pandas as pd
from activation_functions import sigmoid, relu, linear, softmax

In [2]:
X_tstn = np.array([[-0.47,  0.42],
       [-0.47,  3.16]])

W1_tmp = np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
b1_tmp = np.array( [-9.82, -9.28,  0.96] )
W2_tmp = np.array( [[-31.18], [-27.59], [-32.56]] )
b2_tmp = np.array( [15.41] )


In [3]:
X_tstn.shape[0]

2

In [4]:
modeltest = MySequencial([
    DenseLayer(2, activation="linear", layerName="input"), 
    DenseLayer(3, activation='sigmoid', W=W1_tmp, b=b1_tmp, layerName="layer 1"),
    DenseLayer(1, activation='sigmoid', W=W2_tmp, b=b2_tmp, layerName="layer 2")
])


In [5]:
my_predictions = modeltest.predict(X_tstn)
my_predictions
# array([[9.70292454e-01],
#        [3.28294082e-08]])

array([[[9.70292454e-01],
        [3.28294082e-08]]])

In [6]:
yhat = (my_predictions >= 0.5).astype(int)
print(f"decisions = \n{yhat}")

decisions = 
[[1]
 [0]]


In [11]:
df = pd.read_csv("data.csv",header=None)

In [12]:
df

0  1      2      3       4       5        6        7        8   \
0      842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
564    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          9   ...      22     23      24      25       26       27      28  \
0    0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         29      30       31  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 32 columns]

In [9]:
np.diag(np.ones(10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# network = model.createNetwork([
# layers.DenseLayer(input_shape, activation='sigmoid'),
# layers.DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
# layers.DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
# layers.DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
# layers.DenseLayer(output_shape, activation='softmax', weights_initializer='heUniform')
# ])

In [3]:
dense1 = DenseLayer(30, activation="relu", layerName="dense1")
dense1.input_shape

30

In [2]:
model = MySequencial([
    DenseLayer(30, activation="relu", layerName="dense1"), 
    DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
    DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
    DenseLayer(24, activation='sigmoid', weights_initializer='heUniform'),
    DenseLayer(2, activation='softmax', weights_initializer='heUniform')
])


In [54]:
b = np.array([0.1, 0.2, 0.3])

In [55]:
b

array([0.1, 0.2, 0.3])

In [73]:
a = np.array([0.5, 1])

In [67]:
a.transpose()

array([ 0.5, -0.5])

In [79]:
z = W.transpose() @ a + b

In [81]:
def test(z):
    return z + 1
print(z)
test(z)

[4.6 6.2 7.8]


array([5.6, 7.2, 8.8])

In [7]:
X = np.array([[185.32,  12.69],
       [259.92,  11.87],
       [231.01,  14.41],
       [175.37,  11.72],
       [187.12,  14.13],
       [225.91,  12.1 ],
       [208.41,  14.18],
       [207.08,  14.03],
       [280.6 ,  14.23],
       [202.87,  12.25],
       [196.7 ,  13.54],
       [270.31,  14.6 ],
       [192.95,  15.2 ],
       [213.57,  14.28],
       [164.47,  11.92],
       [177.26,  15.04],
       [241.77,  14.9 ],
       [237.  ,  13.13],
       [219.74,  13.87],
       [266.39,  13.25],
       [270.45,  13.95],
       [261.96,  13.49],
       [243.49,  12.86],
       [220.58,  12.36],
       [163.59,  11.65],
       [244.76,  13.33],
       [271.19,  14.84],
       [201.99,  15.39],
       [229.93,  14.56],
       [204.97,  12.28],
       [173.19,  12.22],
       [231.51,  11.95],
       [152.69,  14.83],
       [163.42,  13.3 ],
       [215.95,  13.98],
       [218.04,  15.25],
       [251.3 ,  13.8 ],
       [233.33,  13.53],
       [280.24,  12.41],
       [243.02,  13.72],
       [155.67,  12.68],
       [275.17,  14.64],
       [151.73,  12.69],
       [151.32,  14.81],
       [164.9 ,  11.73],
       [282.55,  13.28],
       [192.98,  11.7 ],
       [202.6 ,  12.96],
       [220.67,  11.53],
       [169.97,  12.34],
       [209.47,  12.71],
       [232.8 ,  12.64],
       [272.8 ,  15.35],
       [158.02,  12.34],
       [226.01,  14.58],
       [158.64,  12.24],
       [211.66,  14.17],
       [271.95,  14.97],
       [257.16,  11.71],
       [281.85,  13.96],
       [161.63,  12.52],
       [233.8 ,  13.04],
       [210.29,  14.72],
       [261.24,  13.69],
       [256.98,  13.12],
       [281.56,  13.92],
       [280.64,  11.68],
       [269.16,  13.74],
       [246.34,  12.27],
       [224.07,  12.66],
       [164.24,  11.51],
       [272.42,  14.18],
       [177.68,  12.53],
       [212.86,  14.77],
       [165.88,  15.37],
       [277.43,  12.48],
       [236.51,  12.94],
       [244.14,  11.85],
       [213.45,  13.85],
       [234.57,  14.27],
       [270.34,  12.47],
       [170.68,  13.06],
       [226.79,  15.34],
       [245.92,  14.45],
       [281.32,  12.57],
       [185.03,  13.19],
       [189.88,  14.1 ],
       [278.48,  12.11],
       [219.92,  14.21],
       [216.58,  15.15],
       [249.48,  15.03],
       [165.09,  12.28],
       [158.87,  14.82],
       [279.98,  11.56],
       [256.55,  14.41],
       [272.61,  12.58],
       [246.49,  12.45],
       [160.26,  14.48],
       [155.7 ,  14.3 ],
       [188.27,  13.45],
       [270.36,  12.47],
       [213.22,  12.92],
       [175.7 ,  13.39],
       [174.52,  14.7 ],
       [233.  ,  12.63],
       [281.37,  12.88],
       [240.62,  14.43],
       [185.81,  11.55],
       [270.5 ,  15.33],
       [172.98,  12.11],
       [208.41,  13.89],
       [283.51,  15.35],
       [283.36,  12.48],
       [230.85,  13.24],
       [181.24,  11.76],
       [172.78,  12.93],
       [161.88,  12.1 ],
       [156.03,  13.99],
       [216.52,  12.47],
       [221.06,  13.2 ],
       [238.99,  15.23],
       [197.69,  14.08],
       [179.55,  15.26],
       [233.39,  12.13],
       [184.7 ,  12.14],
       [174.18,  12.73],
       [261.11,  13.33],
       [187.42,  13.18],
       [186.1 ,  14.43],
       [157.94,  12.66],
       [193.64,  12.23],
       [249.65,  12.22],
       [190.56,  11.73],
       [252.  ,  12.96],
       [238.55,  12.37],
       [152.94,  12.79],
       [255.17,  14.85],
       [197.09,  14.89],
       [156.8 ,  13.59],
       [184.75,  13.26],
       [179.92,  15.07],
       [190.79,  15.28],
       [164.73,  13.22],
       [209.87,  14.34],
       [196.58,  13.47],
       [159.51,  12.74],
       [247.87,  11.92],
       [212.44,  12.45],
       [172.34,  11.99],
       [259.87,  14.25],
       [201.23,  13.07],
       [248.34,  13.92],
       [273.66,  15.18],
       [215.09,  14.14],
       [223.53,  12.74],
       [211.22,  14.38],
       [224.61,  14.03],
       [215.75,  15.31],
       [254.82,  12.02],
       [259.9 ,  15.17],
       [260.25,  12.87],
       [199.67,  12.47],
       [157.52,  13.39],
       [264.81,  14.58],
       [239.4 ,  14.89],
       [238.98,  12.39],
       [258.43,  12.97],
       [270.16,  12.81],
       [162.41,  14.42],
       [164.53,  14.98],
       [205.61,  14.62],
       [157.1 ,  13.68],
       [241.38,  12.02],
       [232.13,  12.07],
       [191.04,  12.96],
       [233.64,  12.02],
       [174.95,  14.63],
       [246.64,  13.32],
       [188.07,  14.27],
       [213.16,  12.75],
       [268.08,  12.31],
       [258.58,  13.97],
       [237.21,  14.23],
       [251.02,  15.02],
       [274.28,  12.52],
       [172.12,  15.09],
       [177.52,  12.39],
       [258.71,  15.36],
       [264.01,  13.57],
       [200.71,  15.45],
       [249.37,  14.02],
       [151.5 ,  12.28],
       [151.82,  15.13],
       [181.92,  12.18],
       [228.65,  12.31],
       [223.78,  15.3 ],
       [266.63,  12.48],
       [273.68,  13.1 ],
       [220.61,  12.8 ],
       [284.99,  12.73]])

In [2]:
Y = np.array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [2]:
# print(f"Temperature Max, Min pre normalization: {np.max(X[:,0]):0.2f}, {np.min(X[:,0]):0.2f}")
# print(f"Duration    Max, Min pre normalization: {np.max(X[:,1]):0.2f}, {np.min(X[:,1]):0.2f}")
# norm_l = tf.keras.layers.Normalization(axis=-1)
# norm_l.adapt(X)  # learns mean, variance
# Xn = norm_l(X)
# print(f"Temperature Max, Min post normalization: {np.max(Xn[:,0]):0.2f}, {np.min(Xn[:,0]):0.2f}")
# print(f"Duration    Max, Min post normalization: {np.max(Xn[:,1]):0.2f}, {np.min(Xn[:,1]):0.2f}")
Xn = np.array([[-0.83, -0.65],
       [ 1.03, -1.39],
       [ 0.31,  0.87],
       [-1.08, -1.52],
       [-0.79,  0.62],
       [ 0.18, -1.18],
       [-0.26,  0.66],
       [-0.29,  0.53],
       [ 1.55,  0.71],
       [-0.4 , -1.05],
       [-0.55,  0.1 ],
       [ 1.29,  1.04],
       [-0.64,  1.57],
       [-0.13,  0.75],
       [-1.36, -1.34],
       [-1.04,  1.42],
       [ 0.58,  1.3 ],
       [ 0.46, -0.27],
       [ 0.03,  0.39],
       [ 1.19, -0.16],
       [ 1.3 ,  0.46],
       [ 1.08,  0.05],
       [ 0.62, -0.51],
       [ 0.05, -0.94],
       [-1.38, -1.57],
       [ 0.65, -0.09],
       [ 1.31,  1.25],
       [-0.42,  1.74],
       [ 0.28,  1.  ],
       [-0.34, -1.02],
       [-1.14, -1.07],
       [ 0.32, -1.31],
       [-1.65,  1.24],
       [-1.38, -0.11],
       [-0.07,  0.49],
       [-0.02,  1.61],
       [ 0.82,  0.33],
       [ 0.37,  0.08],
       [ 1.54, -0.91],
       [ 0.61,  0.26],
       [-1.58, -0.66],
       [ 1.41,  1.07],
       [-1.67, -0.66],
       [-1.69,  1.22],
       [-1.35, -1.51],
       [ 1.6 , -0.13],
       [-0.64, -1.54],
       [-0.4 , -0.41],
       [ 0.05, -1.69],
       [-1.22, -0.97],
       [-0.23, -0.64],
       [ 0.35, -0.7 ],
       [ 1.35,  1.7 ],
       [-1.52, -0.97],
       [ 0.18,  1.02],
       [-1.5 , -1.06],
       [-0.18,  0.66],
       [ 1.33,  1.36],
       [ 0.96, -1.52],
       [ 1.58,  0.47],
       [-1.43, -0.81],
       [ 0.38, -0.34],
       [-0.21,  1.14],
       [ 1.07,  0.23],
       [ 0.96, -0.27],
       [ 1.57,  0.43],
       [ 1.55, -1.56],
       [ 1.26,  0.27],
       [ 0.69, -1.03],
       [ 0.14, -0.69],
       [-1.36, -1.7 ],
       [ 1.35,  0.67],
       [-1.03, -0.8 ],
       [-0.15,  1.19],
       [-1.32,  1.72],
       [ 1.47, -0.84],
       [ 0.45, -0.43],
       [ 0.64, -1.4 ],
       [-0.13,  0.38],
       [ 0.4 ,  0.74],
       [ 1.29, -0.86],
       [-1.2 , -0.33],
       [ 0.2 ,  1.69],
       [ 0.68,  0.91],
       [ 1.57, -0.76],
       [-0.84, -0.21],
       [-0.72,  0.6 ],
       [ 1.5 , -1.17],
       [ 0.03,  0.69],
       [-0.05,  1.53],
       [ 0.77,  1.42],
       [-1.34, -1.02],
       [-1.5 ,  1.23],
       [ 1.53, -1.66],
       [ 0.95,  0.87],
       [ 1.35, -0.75],
       [ 0.7 , -0.87],
       [-1.46,  0.93],
       [-1.58,  0.77],
       [-0.76,  0.02],
       [ 1.29, -0.85],
       [-0.14, -0.45],
       [-1.08, -0.03],
       [-1.1 ,  1.12],
       [ 0.36, -0.71],
       [ 1.57, -0.49],
       [ 0.55,  0.89],
       [-0.82, -1.67],
       [ 1.3 ,  1.68],
       [-1.14, -1.17],
       [-0.26,  0.41],
       [ 1.62,  1.7 ],
       [ 1.62, -0.84],
       [ 0.3 , -0.17],
       [-0.94, -1.48],
       [-1.15, -0.44],
       [-1.42, -1.18],
       [-1.57,  0.5 ],
       [-0.05, -0.85],
       [ 0.06, -0.21],
       [ 0.51,  1.6 ],
       [-0.52,  0.58],
       [-0.98,  1.62],
       [ 0.37, -1.15],
       [-0.85, -1.15],
       [-1.11, -0.62],
       [ 1.06, -0.09],
       [-0.78, -0.23],
       [-0.82,  0.89],
       [-1.52, -0.69],
       [-0.63, -1.07],
       [ 0.78, -1.07],
       [-0.7 , -1.51],
       [ 0.83, -0.42],
       [ 0.5 , -0.94],
       [-1.64, -0.57],
       [ 0.91,  1.26],
       [-0.54,  1.29],
       [-1.55,  0.14],
       [-0.85, -0.15],
       [-0.97,  1.46],
       [-0.7 ,  1.64],
       [-1.35, -0.19],
       [-0.22,  0.8 ],
       [-0.55,  0.03],
       [-1.48, -0.61],
       [ 0.73, -1.34],
       [-0.16, -0.87],
       [-1.16, -1.28],
       [ 1.03,  0.72],
       [-0.44, -0.32],
       [ 0.74,  0.43],
       [ 1.38,  1.55],
       [-0.09,  0.63],
       [ 0.12, -0.61],
       [-0.19,  0.85],
       [ 0.15,  0.53],
       [-0.07,  1.67],
       [ 0.9 , -1.25],
       [ 1.03,  1.54],
       [ 1.04, -0.49],
       [-0.48, -0.85],
       [-1.53, -0.04],
       [ 1.15,  1.01],
       [ 0.52,  1.29],
       [ 0.51, -0.92],
       [ 0.99, -0.41],
       [ 1.29, -0.55],
       [-1.41,  0.88],
       [-1.35,  1.37],
       [-0.33,  1.05],
       [-1.54,  0.22],
       [ 0.57, -1.25],
       [ 0.34, -1.2 ],
       [-0.69, -0.42],
       [ 0.37, -1.25],
       [-1.09,  1.06],
       [ 0.7 , -0.1 ],
       [-0.77,  0.74],
       [-0.14, -0.61],
       [ 1.24, -1.  ],
       [ 1.  ,  0.48],
       [ 0.46,  0.71],
       [ 0.81,  1.41],
       [ 1.39, -0.81],
       [-1.16,  1.47],
       [-1.03, -0.92],
       [ 1.  ,  1.71],
       [ 1.13,  0.12],
       [-0.45,  1.79],
       [ 0.77,  0.52],
       [-1.68, -1.02],
       [-1.67,  1.5 ],
       [-0.92, -1.1 ],
       [ 0.25, -0.99],
       [ 0.13,  1.66],
       [ 1.2 , -0.84],
       [ 1.38, -0.3 ],
       [ 0.05, -0.56],
       [ 1.66, -0.62]])

In [4]:
def my_dense(a_in, W, b):
    """
    Computes dense layer
    Args:
      a_in (ndarray (n, )) : Data, 1 example 
      W    (ndarray (n,j)) : Weight matrix, n features per unit, j units
      b    (ndarray (j, )) : bias vector, j units  
    Returns
      a_out (ndarray (j,))  : j units|
    """
    units = W.shape[1]
    a_out = np.zeros(units)
    for j in range(units):               
        w = W[:,j]                                    
        z = np.dot(w, a_in) + b[j]         
        a_out[j] = g(z)               
    return(a_out)

In [5]:
def my_sequential(x, W1, b1, W2, b2):
    a1 = my_dense(x,  W1, b1)
    a2 = my_dense(a1, W2, b2)
    return(a2)

In [6]:
g = sigmoid

In [2]:
W1_tmp = np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
b1_tmp = np.array( [-9.82, -9.28,  0.96] )
W2_tmp = np.array( [[-31.18], [-27.59], [-32.56]] )
b2_tmp = np.array( [15.41] )

In [8]:
def my_predict(X, W1, b1, W2, b2):
    m = X.shape[0]
    p = np.zeros((m,1))
    for i in range(m):
        p[i,0] = my_sequential(X[i], W1, b1, W2, b2)
    return(p)

In [5]:
X_tst = np.array([
    [200,13.9],  # postive example
    [200,17]])   # negative example





In [ ]:
predictions = my_predict(X_tstn, W1_tmp, b1_tmp, W2_tmp, b2_tmp)

In [10]:
predictions
array([[9.70292454e-01],
       [3.28294082e-08]])

array([[9.70292454e-01],
       [3.28294082e-08]])

In [11]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0
print(f"decisions = \n{yhat}")

decisions = 
[[1.]
 [0.]]


In [12]:
yhat = (predictions >= 0.5).astype(int)
print(f"decisions = \n{yhat}")

decisions = 
[[1]
 [0]]


In [3]:
modeltest = MySequencial([
    DenseLayer(2, activation="linear", layerName="input"), 
    DenseLayer(3, activation='sigmoid', W=W1_tmp, b=b1_tmp, layerName="layer 1"),
    DenseLayer(1, activation='sigmoid', W=W2_tmp, b=b2_tmp, layerName="layer 2")
])


In [15]:
modeltest.summary()

----------- Layer 1 -----------
Layer Name: input
Shape W: (2, 2)
W: [[1. 0.]
 [0. 1.]]
Shape b: (2,)
b: [0. 0.]
activation: <function linear at 0x7fbac2267400>
weights_initializer: <function heUniformWI at 0x7fbac2267b50> 

----------- Layer 2 -----------
Layer Name: Dense
Shape W: (2, 3)
W: [[-8.93  0.29 12.9 ]
 [-0.1  -7.32 10.81]]
Shape b: (3,)
b: [-9.82 -9.28  0.96]
activation: <function sigmoid at 0x7fbac22672e0>
weights_initializer: <function heUniformWI at 0x7fbac2267b50> 

----------- Layer 3 -----------
Layer Name: Dense
Shape W: (3, 1)
W: [[-31.18]
 [-27.59]
 [-32.56]]
Shape b: (1,)
b: [15.41]
activation: <function sigmoid at 0x7fbac22672e0>
weights_initializer: <function heUniformWI at 0x7fbac2267b50> 

