In [28]:
import matplotlib.pyplot as plt
import numpy as np
from MySequencial import MySequencial
from DenseLayer import DenseLayer
import pandas as pd
from LossFunctions import setLossFunction, binaryCrossentropyLoss, sparseCategoricalCrossEntropyLoss
import pickle

In [24]:
df = pd.read_csv("wheat-seeds.csv",header=None)

In [14]:
df.iloc[:,-1] -= 1

In [15]:
myModel = MySequencial([
    DenseLayer(7, activation="linear"), 
    DenseLayer(8, activation='sigmoid'),
    DenseLayer(8, activation='sigmoid'),
    DenseLayer(3, activation='softmax')
])

In [16]:
data = df.to_numpy()

In [17]:
np.random.shuffle(data)

In [18]:
data_train = data[:int(len(data) * 0.75),:]
data_val = data[int(len(data) * 0.75):,:]

In [19]:
# X_train = data[:, :-1]
# y_train = data[:, -1]
# y_pred = myModel.predict(X_train)
# y_pred = np.clip(y_pred, 1e-15, 1 - 1e-15)
# m = y_train.shape[0]

# y_pred[np.arange(m), y_train.astype(int)]

# loss = -1/m * np.sum(np.log(y_pred[np.arange(m), y_train]))
# return loss

# def sparse_categorical_cross_entropy_loss(y_true, y_pred):
#     # Assurez-vous que les prédictions ne sont pas nulles
#     y_pred = np.clip(y_pred, 1e-15, 1 - 1e-15)
    
#     # Nombre d'échantillons
#     m = y_true.shape[0]
    
#     # Extraire les probabilités prédites pour les classes correctes
#     # Utilisez y_true comme indice pour sélectionner la probabilité prédite pour chaque exemple
#     correct_probs = y_pred[np.arange(m), y_true]
    
#     # Calcul de la perte
#     loss = -1/m * np.sum(np.log(correct_probs))
    
#     return loss



In [22]:
myModel.fit(data_train, data_val, batch_size=8, epochs=350, loss="sparseCategoricalCrossEntropyLoss")

epoch 0 : 20/20 - accuracy: 87.9, loss:0.3, val accuracy: 92.45, val loss: 0.238
epoch 1 : 20/20 - accuracy: 91.08, loss:0.289, val accuracy: 94.34, val loss: 0.231
epoch 2 : 20/20 - accuracy: 87.9, loss:0.304, val accuracy: 92.45, val loss: 0.246
epoch 3 : 20/20 - accuracy: 92.36, loss:0.288, val accuracy: 94.34, val loss: 0.227
epoch 4 : 20/20 - accuracy: 89.81, loss:0.291, val accuracy: 94.34, val loss: 0.221
epoch 5 : 20/20 - accuracy: 92.36, loss:0.287, val accuracy: 94.34, val loss: 0.227
epoch 6 : 20/20 - accuracy: 89.17, loss:0.303, val accuracy: 94.34, val loss: 0.248
epoch 7 : 20/20 - accuracy: 89.81, loss:0.291, val accuracy: 96.23, val loss: 0.222
epoch 8 : 20/20 - accuracy: 88.54, loss:0.299, val accuracy: 94.34, val loss: 0.247
epoch 9 : 20/20 - accuracy: 87.9, loss:0.298, val accuracy: 92.45, val loss: 0.233
epoch 10 : 20/20 - accuracy: 89.81, loss:0.292, val accuracy: 96.23, val loss: 0.226
epoch 11 : 20/20 - accuracy: 89.17, loss:0.288, val accuracy: 94.34, val loss: 0

In [27]:
np.argmax(myModel.predict(data_train[:,:-1]), axis=1) == data_train[:, -1]

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [25]:
data_train[:, -1]

array([2., 0., 2., 0., 1., 2., 2., 1., 0., 1., 2., 0., 2., 1., 0., 0., 2.,
       0., 1., 0., 1., 0., 1., 0., 2., 0., 0., 0., 0., 1., 2., 0., 2., 2.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 2., 0., 1., 1., 2., 0., 2.,
       2., 0., 1., 1., 0., 0., 2., 2., 2., 1., 2., 1., 2., 1., 2., 2., 2.,
       2., 0., 1., 1., 1., 1., 2., 1., 2., 0., 1., 2., 2., 0., 0., 2., 2.,
       1., 0., 1., 1., 0., 2., 0., 0., 0., 0., 0., 1., 0., 1., 2., 1., 0.,
       1., 2., 2., 1., 0., 1., 2., 1., 2., 0., 1., 2., 2., 2., 0., 0., 1.,
       0., 1., 2., 2., 2., 1., 1., 2., 2., 1., 0., 0., 2., 2., 0., 1., 2.,
       0., 2., 0., 1., 0., 2., 2., 1., 0., 1., 1., 1., 2., 1., 2., 0., 0.,
       2., 0., 1., 2.])

In [34]:
# binaryCrossentropyLoss(myModel,data_train[:,:-1], data_train[:, -1])
f_tab = myModel.predict(data_train[:,:-1])
y_pred = f_tab[:,1]
y_pred

array([6.79377638e-04, 8.71692897e-02, 7.80683794e-04, 4.41164861e-03,
       9.48791838e-01, 9.68229007e-04, 5.58161855e-03, 9.37818084e-01,
       3.28447136e-01, 9.45269698e-01, 6.86666562e-04, 3.45742307e-02,
       1.24838790e-02, 7.09408966e-01, 2.66808354e-02, 8.63147388e-01,
       2.26714776e-03, 1.59680045e-01, 9.53918838e-01, 4.88285514e-02,
       9.28853951e-01, 3.26996101e-03, 9.14464602e-01, 4.04573125e-02,
       6.43471881e-04, 2.89363247e-02, 6.30525580e-02, 2.58004548e-01,
       2.03683707e-02, 8.97066100e-01, 8.71826635e-04, 2.68630650e-02,
       6.41591768e-03, 1.57510463e-03, 1.19642766e-01, 9.43908220e-01,
       8.42844727e-02, 9.42072469e-01, 2.94480449e-01, 9.53585025e-01,
       9.44929190e-01, 8.86983544e-01, 8.17877825e-01, 9.39756433e-01,
       2.55306419e-03, 8.44285766e-02, 8.92910805e-01, 7.29787385e-01,
       1.21249421e-03, 8.56523513e-02, 7.10382355e-04, 7.19832018e-04,
       7.47984677e-02, 8.64852758e-01, 1.10921885e-01, 3.63250235e-02,
      

In [18]:
lossFunction = setLossFunction("binaryCrossentropy")
lossTrain = []
lossVal = []
X_val = data_val[:, :-1]
y_val = data_val[:, -1]
# assert batch_size > 0, "batch_size need to be > 0"
nb_batch = int(len(data_train) / batch_size)  + 1
if len(data_train) % batch_size == 0:
    nb_batch = nb_batch - 1

In [19]:
nb_batch

20

In [20]:
epoch = 0
data = data_train.copy()
np.random.shuffle(data)
X_train = data[:, :-1]
y_train = data[:, -1]
X_batchs = [X_train[i:i+batch_size] for i in range(0, len(X_train), batch_size)]
y_batchs = [y_train[i:i+batch_size] for i in range(0, len(y_train), batch_size)]
num_batch = 0


In [21]:
# for X_batch, y_batch in zip(X_batchs, y_batchs):
X_batch = X_batchs[0]
y_batch = y_batchs[0]
num_batch += 1
# self.back_propag(X_batch, y_batch, alpha)
myModel.predict(X_batch)

array([[0.67406175, 0.05008242, 0.27585583],
       [0.65909509, 0.05185414, 0.28905077],
       [0.70495815, 0.04588015, 0.2491617 ],
       [0.66895014, 0.05102814, 0.28002172],
       [0.72875896, 0.04309287, 0.22814817],
       [0.71140395, 0.0451014 , 0.24349465],
       [0.71691427, 0.04475614, 0.23832959],
       [0.71389198, 0.04489398, 0.24121404]])

In [22]:
myModel.layers[-1].setErrorLastLayer(y_batch)

In [31]:
previousLayer = myModel.layers[-1]

In [54]:
i = 1
# myModel.layers[i].setError(previousLayer) ==> erreur
curentLayer = myModel.layers[i]
curentLayer.errors = previousLayer.delta @ previousLayer.W.T


In [55]:
curentLayer.errors

array([[-0.14914498,  0.09778302, -0.22836575,  0.25271304,  0.15099635,
        -0.02988386,  0.05476367, -0.05494796],
       [-0.14704088,  0.09519577, -0.22475397,  0.25407174,  0.1468891 ,
        -0.02745019,  0.0559438 , -0.05311208],
       [ 0.04330027, -0.04839115,  0.0705633 ,  0.00874016, -0.07497661,
         0.03962655,  0.01565427,  0.03082548],
       [-0.1484485 ,  0.09694154, -0.2271391 ,  0.25309273,  0.14963501,
        -0.02906436,  0.05514303, -0.05430932],
       [-0.09687332,  0.12054808, -0.16178471, -0.06965247,  0.1878146 ,
        -0.10906663, -0.05486738, -0.07969164],
       [ 0.04228864, -0.04721246,  0.06903429,  0.0083053 , -0.07324483,
         0.03876654,  0.01525914,  0.03022875],
       [-0.09556474,  0.11926453, -0.1590151 , -0.07029484,  0.18533406,
        -0.10741647, -0.05443456, -0.07806496],
       [ 0.04190365, -0.04675598,  0.0684507 ,  0.00810733, -0.07257343,
         0.03842696,  0.01509627,  0.02999572]])

In [44]:
previousLayer.W

array([[-0.21730289,  0.78066008,  0.40182529],
       [ 0.17088151, -0.59579319, -0.59583497],
       [-0.76542164,  0.63423569,  0.17513634],
       [ 0.36039228, -0.83037201,  0.81390774],
       [ 0.57580754, -0.49824328, -0.55109532],
       [-0.54835947, -0.33906238,  0.0428794 ],
       [-0.11787469, -0.36160174,  0.1937349 ],
       [-0.62441495, -0.36001603, -0.23146808]])

In [45]:
previousLayer.delta

array([[ 0.16702869, -0.17461135,  0.05839091],
       [ 0.16294439, -0.1747633 ,  0.06171373],
       [-0.07339575,  0.00837987,  0.05178699],
       [ 0.16563736, -0.17464567,  0.05943847],
       [ 0.18169531,  0.00783219, -0.15804055],
       [-0.07184058,  0.00822677,  0.05040789],
       [ 0.17855838,  0.00815633, -0.15711009],
       [-0.07123883,  0.00818526,  0.04985585]])

In [46]:
curentLayer.input 

array([[17.98  , 15.85  ,  0.8993,  5.979 ,  3.687 ,  2.257 ,  5.919 ],
       [19.15  , 16.45  ,  0.889 ,  6.245 ,  3.815 ,  3.084 ,  6.185 ],
       [14.11  , 14.18  ,  0.882 ,  5.541 ,  3.221 ,  2.754 ,  5.038 ],
       [20.1   , 16.99  ,  0.8746,  6.581 ,  3.785 ,  1.955 ,  6.449 ],
       [10.82  , 12.83  ,  0.8256,  5.18  ,  2.63  ,  4.853 ,  5.089 ],
       [14.01  , 14.29  ,  0.8625,  5.609 ,  3.158 ,  2.217 ,  5.132 ],
       [11.02  , 13.    ,  0.8189,  5.325 ,  2.701 ,  6.735 ,  5.163 ],
       [13.02  , 13.76  ,  0.8641,  5.395 ,  3.026 ,  3.373 ,  4.825 ]])

In [53]:
previousLayer.W

array([[-0.21730289,  0.78066008,  0.40182529],
       [ 0.17088151, -0.59579319, -0.59583497],
       [-0.76542164,  0.63423569,  0.17513634],
       [ 0.36039228, -0.83037201,  0.81390774],
       [ 0.57580754, -0.49824328, -0.55109532],
       [-0.54835947, -0.33906238,  0.0428794 ],
       [-0.11787469, -0.36160174,  0.1937349 ],
       [-0.62441495, -0.36001603, -0.23146808]])

In [50]:
curentLayer.output

array([[2.33214780e-03, 1.00000000e+00, 3.21363874e-02, 1.00000000e+00,
        8.79628652e-01, 7.93633979e-11, 3.91080295e-10, 9.65381654e-01],
       [1.01196199e-03, 1.00000000e+00, 1.88335967e-02, 1.00000000e+00,
        8.11105924e-01, 3.12075169e-11, 9.17015848e-11, 9.78840967e-01],
       [4.15574496e-03, 9.99999998e-01, 7.13478848e-03, 9.99999999e-01,
        9.29364239e-01, 2.86598608e-09, 1.40023647e-08, 7.91924487e-01],
       [2.02647936e-03, 1.00000000e+00, 4.59852386e-02, 1.00000000e+00,
        8.77505071e-01, 8.59294792e-12, 5.07411263e-11, 9.84141217e-01],
       [2.71468476e-03, 9.99999878e-01, 7.33108490e-04, 9.99999999e-01,
        9.56302814e-01, 2.03907471e-07, 1.72834378e-07, 5.78050479e-01],
       [6.69917540e-03, 9.99999998e-01, 9.74520796e-03, 9.99999999e-01,
        9.55002550e-01, 2.63262649e-09, 1.74626333e-08, 7.73481411e-01],
       [6.76259882e-04, 9.99999910e-01, 1.42038870e-04, 1.00000000e+00,
        9.07241479e-01, 2.57233545e-07, 7.38079397e-08, 5.

In [51]:
previousLayer.delta @ previousLayer.W

array([[-0.14914498,  0.09778302, -0.22836575,  0.25271304,  0.15099635,
        -0.02988386,  0.05476367, -0.05494796],
       [-0.14704088,  0.09519577, -0.22475397,  0.25407174,  0.1468891 ,
        -0.02745019,  0.0559438 , -0.05311208],
       [ 0.04330027, -0.04839115,  0.0705633 ,  0.00874016, -0.07497661,
         0.03962655,  0.01565427,  0.03082548],
       [-0.1484485 ,  0.09694154, -0.2271391 ,  0.25309273,  0.14963501,
        -0.02906436,  0.05514303, -0.05430932],
       [-0.09687332,  0.12054808, -0.16178471, -0.06965247,  0.1878146 ,
        -0.10906663, -0.05486738, -0.07969164],
       [ 0.04228864, -0.04721246,  0.06903429,  0.0083053 , -0.07324483,
         0.03876654,  0.01525914,  0.03022875],
       [-0.09556474,  0.11926453, -0.1590151 , -0.07029484,  0.18533406,
        -0.10741647, -0.05443456, -0.07806496],
       [ 0.04190365, -0.04675598,  0.0684507 ,  0.00810733, -0.07257343,
         0.03842696,  0.01509627,  0.02999572]])

In [39]:
myModel.predict(data_train[:,:-1])

array([[3.16555962e-02, 6.79377638e-04, 9.67665026e-01],
       [8.09320701e-01, 8.71692897e-02, 1.03510009e-01],
       [3.26573893e-02, 7.80683794e-04, 9.66561927e-01],
       [2.82293280e-01, 4.41164861e-03, 7.13295072e-01],
       [5.05490964e-02, 9.48791838e-01, 6.59065822e-04],
       [4.42198322e-02, 9.68229007e-04, 9.54811939e-01],
       [3.10610207e-01, 5.58161855e-03, 6.83808174e-01],
       [6.14958192e-02, 9.37818084e-01, 6.86096770e-04],
       [6.53599415e-01, 3.28447136e-01, 1.79534487e-02],
       [5.41261507e-02, 9.45269698e-01, 6.04151364e-04],
       [3.39221530e-02, 6.86666562e-04, 9.65391180e-01],
       [8.22914131e-01, 3.45742307e-02, 1.42511638e-01],
       [8.35212397e-02, 1.24838790e-02, 9.03994881e-01],
       [2.84343469e-01, 7.09408966e-01, 6.24756490e-03],
       [8.22238129e-01, 2.66808354e-02, 1.51081036e-01],
       [1.34951163e-01, 8.63147388e-01, 1.90144905e-03],
       [8.36345159e-02, 2.26714776e-03, 9.14098336e-01],
       [7.42909689e-01, 1.59680

In [40]:
data_train[:,:-1]

array([[11.19  , 13.05  ,  0.8253,  5.25  ,  2.675 ,  5.813 ,  5.219 ],
       [14.69  , 14.49  ,  0.8799,  5.563 ,  3.259 ,  3.586 ,  5.219 ],
       [11.14  , 12.79  ,  0.8558,  5.011 ,  2.794 ,  6.388 ,  5.049 ],
       [11.42  , 12.86  ,  0.8683,  5.008 ,  2.85  ,  2.7   ,  4.607 ],
       [19.14  , 16.61  ,  0.8722,  6.259 ,  3.737 ,  6.682 ,  6.053 ],
       [12.19  , 13.36  ,  0.8579,  5.24  ,  2.909 ,  4.857 ,  5.158 ],
       [12.62  , 13.67  ,  0.8481,  5.41  ,  2.911 ,  3.306 ,  5.231 ],
       [18.81  , 16.29  ,  0.8906,  6.272 ,  3.693 ,  3.237 ,  6.053 ],
       [16.44  , 15.25  ,  0.888 ,  5.884 ,  3.505 ,  1.969 ,  5.533 ],
       [18.89  , 16.23  ,  0.9008,  6.227 ,  3.769 ,  3.639 ,  5.966 ],
       [10.8   , 12.57  ,  0.859 ,  4.981 ,  2.821 ,  4.773 ,  5.063 ],
       [14.11  , 14.26  ,  0.8722,  5.52  ,  3.168 ,  2.688 ,  5.219 ],
       [12.7   , 13.41  ,  0.8874,  5.183 ,  3.091 ,  8.456 ,  5.    ],
       [16.23  , 15.18  ,  0.885 ,  5.872 ,  3.472 ,  3.769 ,  5

In [26]:
myModel

In [29]:
with open("my_model.pkl", 'wb') as f:
    pickle.dump(myModel, f)

In [30]:
with open('my_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)


In [32]:
loaded_model.layers[2].W

array([[-0.52385216,  1.08944542,  0.2442697 ,  0.38665219, -0.38420246,
        -0.64359113, -0.79639527,  0.5914137 ],
       [ 0.37115738,  0.32134918, -0.68525358,  0.8679324 ,  0.47645947,
        -0.29638172, -0.47612836, -0.5848817 ],
       [-0.37679555, -0.3125585 , -1.3671208 , -2.09166546,  2.22156596,
        -1.11600502, -1.81964792, -0.63243539],
       [ 0.11993206,  0.45489615, -0.37506173,  0.07867955,  0.06071849,
        -0.58370932,  0.26124022, -0.60719116],
       [-1.90683955,  2.32174721,  1.07414983,  2.56149343, -0.89586472,
        -0.41545526,  1.34376972, -0.0199011 ],
       [-0.65464892, -0.00835384, -0.80646254,  0.70896396, -0.41780563,
         0.28149695, -0.32612578,  0.03475889],
       [ 0.08090457, -0.54584805,  0.81334457,  0.47654429,  0.76123428,
         0.6838611 ,  0.16956792,  0.73070765],
       [ 0.10943854, -1.70394873, -1.31113899, -1.9791037 ,  0.72289348,
        -0.57924754, -0.47287431, -0.44287366]])

In [33]:
myModel.layers[2].W

array([[-0.52385216,  1.08944542,  0.2442697 ,  0.38665219, -0.38420246,
        -0.64359113, -0.79639527,  0.5914137 ],
       [ 0.37115738,  0.32134918, -0.68525358,  0.8679324 ,  0.47645947,
        -0.29638172, -0.47612836, -0.5848817 ],
       [-0.37679555, -0.3125585 , -1.3671208 , -2.09166546,  2.22156596,
        -1.11600502, -1.81964792, -0.63243539],
       [ 0.11993206,  0.45489615, -0.37506173,  0.07867955,  0.06071849,
        -0.58370932,  0.26124022, -0.60719116],
       [-1.90683955,  2.32174721,  1.07414983,  2.56149343, -0.89586472,
        -0.41545526,  1.34376972, -0.0199011 ],
       [-0.65464892, -0.00835384, -0.80646254,  0.70896396, -0.41780563,
         0.28149695, -0.32612578,  0.03475889],
       [ 0.08090457, -0.54584805,  0.81334457,  0.47654429,  0.76123428,
         0.6838611 ,  0.16956792,  0.73070765],
       [ 0.10943854, -1.70394873, -1.31113899, -1.9791037 ,  0.72289348,
        -0.57924754, -0.47287431, -0.44287366]])